stages:
    - build
variables:
    VERSION: alpine
    LOADED_IMAGE: gitlab/gitlab-runner
    HELPER_IMAGE: gitlab/gitlab-runner-helper
    HELPER_TAG: x86_64-4745a6f3
    
before_script: 
    # - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
    stage: build
    script:
        - docker load -i gitlab_runner
        - docker tag $LOADED_IMAGE:latest $CI_REGISTRY_IMAGE:latest
        - docker tag $LOADED_IMAGE:$VERSION $CI_REGISTRY_IMAGE:$VERSION
        - docker tag $HELPER_IMAGE:$HELPER_TAG $CI_REGISTRY_IMAGE/helper:$HELPER_TAG
        - docker images
        - docker push $CI_REGISTRY_IMAGE:$VERSION 
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE/helper:$HELPER_TAG
        - docker rmi $CI_REGISTRY_IMAGE:$VERSION $CI_REGISTRY_IMAGE:latest $LOADED_IMAGE:latest 